root: true
ignorePatterns:
  - node_modules/
env:
  es6: true
  node: true
extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - prettier
  - prettier/@typescript-eslint
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
plugins:
  - '@typescript-eslint'
  - prettier
  - functional
  - simple-import-sort
rules:
  eqeqeq:
    - error
    - always
    - null: ignore
  linebreak-style: [error, unix]
  no-console: error
  quotes: [error, single, { avoidEscape: true }]
  semi: [error, never]
  'prettier/prettier': error
  'import/newline-after-import': error
  'simple-import-sort/sort':
    - error
    # configuration based on https://github.com/lydell/eslint-plugin-simple-import-sort/blob/master/examples/.eslintrc.js#L74
    - groups: [
          # Node.js builtins
          [
            '^(assert|buffer|child_process|cluster|console|constants|crypto|dgram|dns|domain|events|fs|http|https|module|net|os|path|punycode|querystring|readline|repl|stream|string_decoder|sys|timers|tls|tty|url|util|vm|zlib|freelist|v8|process|async_hooks|http2|perf_hooks)(/.*|$)',
          ],
          # packages
          ["^@?\\w"],
          # side effect imports
          ["^\\u0000"],
          # parent imports (put `..` last)
          ["^\\.\\.(?!/?$)", "^\\.\\./?$"],
          # other relative imports (put same-folder imports and `.` last)
          ["^\\./(?=.*/)(?!/?$)", "^\\.(?!/?$)", "^\\./?$"],
        ]
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/explicit-member-accessibility': error
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: ^_
  '@typescript-eslint/no-use-before-define': off
  '@typescript-eslint/member-ordering': error
  'functional/immutable-data': error
  'functional/no-let': error
  'functional/no-loop-statement': error
